---
platform: linux

image_resource:
  type: docker-image
  source: { repository: docker.***REMOVED***/monsoon/gobuild, tag: '1.6'}

inputs:
- name: cli.version
- name: cli.git 
  path: gopath/src/github.com/sapcc/lyra-cli

outputs:
- name: binary

run:
  path: gopath/src/github.com/sapcc/lyra-cli/ci/build
params:
  GOOS: linux
